
--Basic Sudoku Table
CREATE TABLE SUDOKU
(
  RW_NO NUMBER(1),
  CL_NO NUMBER(1),
  VL_VL NUMBER(1),
  Constraint PK_SUDOKU PRIMARY KEY (RW_NO, CL_NO)
);

--User Defined Block(s) 
CREATE TABLE SUDOKU_BLOCK
(
  RW_NO NUMBER(1),
  CL_NO NUMBER(1),
  BLKNO NUMBER(1) --specifies which block tht particular row/column belongs
);

-- All Possible values that a Sudoku Field can take
CREATE TABLE SUDOKU_ALLPOSSIBLE_VALUES
(
  RW_NO NUMBER(1),
  CL_NO NUMBER(1),
  BLKNO NUMBER(1), 
  VL_VL NUMBER(1)
);


--Blocks DML
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (1,1,1);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (1,2,1);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (1,3,2);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (1,4,2);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (1,5,2);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (1,6,2);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (1,7,3);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (1,8,3);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (1,9,3);

INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (2,1,1);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (2,2,2);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (2,3,2);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (2,4,2);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (2,5,3);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (2,6,2);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (2,7,3);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (2,8,4);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (2,9,3);

INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (3,1,1);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (3,2,1);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (3,3,1);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (3,4,2);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (3,5,3);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (3,6,3);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (3,7,3);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (3,8,4);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (3,9,4);

INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (4,1,5);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (4,2,5);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (4,3,1);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (4,4,6);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (4,5,6);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (4,6,6);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (4,7,4);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (4,8,4);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (4,9,4);

INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (5,1,5);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (5,2,1);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (5,3,1);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (5,4,6);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (5,5,6);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (5,6,6);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (5,7,7);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (5,8,7);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (5,9,4);

INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (6,1,5);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (6,2,5);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (6,3,5);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (6,4,6);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (6,5,6);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (6,6,6);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (6,7,7);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (6,8,4);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (6,9,4);

INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (7,1,5);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (7,2,5);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (7,3,8);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (7,4,8);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (7,5,8);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (7,6,9);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (7,7,7);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (7,8,7);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (7,9,7);

INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (8,1,8);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (8,2,5);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (8,3,8);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (8,4,9);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (8,5,8);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (8,6,9);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (8,7,9);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (8,8,9);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (8,9,7);

INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (9,1,8);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (9,2,8);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (9,3,8);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (9,4,9);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (9,5,9);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (9,6,9);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (9,7,9);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (9,8,7);
INSERT INTO SUDOKU_BLOCK (RW_NO, CL_NO, BLKNO) VALUES (9,9,7);
