-- Sudoku Puzzle Setup

INSERT INTO SUDOKU (RW_NO, CL_NO, VL_VL) VALUES (1,3,4);
INSERT INTO SUDOKU (RW_NO, CL_NO, VL_VL) VALUES (2,2,8);
INSERT INTO SUDOKU (RW_NO, CL_NO, VL_VL) VALUES (2,8,6);
INSERT INTO SUDOKU (RW_NO, CL_NO, VL_VL) VALUES (3,4,9);
INSERT INTO SUDOKU (RW_NO, CL_NO, VL_VL) VALUES (3,5,4);
INSERT INTO SUDOKU (RW_NO, CL_NO, VL_VL) VALUES (3,8,1);
INSERT INTO SUDOKU (RW_NO, CL_NO, VL_VL) VALUES (4,4,3);
INSERT INTO SUDOKU (RW_NO, CL_NO, VL_VL) VALUES (4,5,5);
INSERT INTO SUDOKU (RW_NO, CL_NO, VL_VL) VALUES (5,3,6);
INSERT INTO SUDOKU (RW_NO, CL_NO, VL_VL) VALUES (5,7,5);
INSERT INTO SUDOKU (RW_NO, CL_NO, VL_VL) VALUES (6,5,6);
INSERT INTO SUDOKU (RW_NO, CL_NO, VL_VL) VALUES (6,6,2);
INSERT INTO SUDOKU (RW_NO, CL_NO, VL_VL) VALUES (7,2,9);
INSERT INTO SUDOKU (RW_NO, CL_NO, VL_VL) VALUES (7,5,3);
INSERT INTO SUDOKU (RW_NO, CL_NO, VL_VL) VALUES (7,6,6);
INSERT INTO SUDOKU (RW_NO, CL_NO, VL_VL) VALUES (8,2,2);
INSERT INTO SUDOKU (RW_NO, CL_NO, VL_VL) VALUES (8,8,9);
INSERT INTO SUDOKU (RW_NO, CL_NO, VL_VL) VALUES (9,7,7);
